# SonarQube / SonarLint Configuration
sonar.python.version=3.12
sonar.sources=src/
sonar.tests=tests/
sonar.python.coverage.reportPaths=reports/coverage-unit.xml,reports/coverage-integration.xml
sonar.python.xunit.reportPath=reports/junit-unit.xml
